### ISSUE TITLE
Enable listening on / instead of just /speedtest

### ISSUE THREAD

**Issue by ordinarygulp** [moranbw/speedtest-app#1]
Currently get an error if I just load the docker container url or proxy with a subdomain (speedtest.example.com), so I am forced to do speedtest.example.com/speedtest.

**Comment by moranbw** [comment]
This is a good point and I should give you the option to go root or relative path for deployment. I will get to this at some point this week and update here.

**Comment by moranbw** [comment]
@d2dyno I think the latest release should have fixed this issue.  additionally, I have updated the README to explain how one could proxy to a sub-directory (like /speedtest).  I think it makes sense to just serve from root by default, then let a proxy handle the rest if you need something different. 

Let me know and I will close the issue.

**Comment by moranbw** [comment]
in case anyone winds up here, nginx proxy examples:

****sub-directory****
location = /speedtest {
    return 302 /speedtest/;
}
location /speedtest/ {
    proxy_pass http://your_ip_or_host:5000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

****standard / sub-domain****
location / {
    proxy_pass http://your_ip_or_host:5000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

**Comment by ordinarygulp** [comment]
Yes, working perfectly as requested, thanks so much for the quick turnaround!
